title: "NASA SMAP Sea Surface Salinity (SSS)"
description: "Analysis-ready Zarr datasets derived from NASA SMAP Sea Surface Salinity (SSS) Level 3 Gridded NetCDFs"
pangeo_forge_version: "0.3.3"
recipes:
  - dict-object: "recipe:recipes"
provenance:
  providers:
    - name: "NASA SMAP"
      description: "National Aeronautics and Space Administration Soil Moisture Active Passive Mission"
      roles:
        - producer
        - licensor
      url: https://smap.jpl.nasa.gov/
  license: "CC-BY-4.0" # TODO: double-check before merging
maintainers:
  - name: "Charles Stern"
    github: cisaacstern
bakery:
  id: "devseed.bakery.development.aws.us-west-2"  # must come from a valid list of bakeries
  target: pangeo-forge-aws-bakery-flowcachebucketpangeofor-196cpck7y0pbl
  resources:
    memory: 4096
    cpu: 1024