title: "eVolv2k VSSI database"
description: "eVolv2k version 3 includes estimates of the magnitudes and approximate source latitudes of major volcanic stratospheric sulfur injection (VSSI) events from 500 BCE to 1900 CE."
pangeo_forge_version: "0.9.0"
pangeo_notebook_version: "2022.06.02"
recipes:
  - id: eVolv2k_v3
    object: "recipe:recipe"
provenance:
  providers:
    - name: "WDCC"
      description: "World Data Center for Climate"
      roles:
        - licensor
        - curator
      url: "https://www.wdc-climate.de/ui/entry?acronym=eVolv2k_v3"
  license: "Creative Commons Attribution 4.0 International"
maintainers:
  - name: "Jordan Landers"
    orcid: "0000-0001-9772-7617"
    github: jordanplanders
bakery:
  id: "pangeo-ldeo-nsf-earthcube"


