name: Recipe Comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  push-notebook:
    runs-on: ubuntu-latest
    outputs:
      repo-link: ${{ steps.repo-link.outputs.link }}
    steps:
      #- id: push-test-notebook
      #  run: push-test-notebook.sh --PR=${{ github.event.issue.number }} --run-id=${{ github.event.comment.id }}
      - id: repo-link
        run: echo "::set-output name=link::https://binder.pangeo.io/v2/gh/pangeo-forge/recipe-test-notebooks/main?filepath=${{ github.event.issue.number }}%2F${{ github.event.comment.id }}.ipynb"

  binder-link:
    runs-on: ubuntu-latest
    needs: push-notebook
    outputs:
      link: ${{ steps.binder.outputs.link }}
    steps:
      - id: binder
        run: echo "::set-output name=link::[![Binder](https://binder.pangeo.io/badge_logo.svg)](${{ needs.push-notebook.outputs.repo-link }})"

  comment-on-pr:
    runs-on: ubuntu-latest
    needs: binder-link
    steps:
      - name: Create comment
        if: |
          github.event.issue.pull_request && contains(github.event.comment.body, '/run-recipe-test') && endsWith(github.event.comment.body, ':white_check_mark:')
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ contains(github.event.comment.body, '/run-recipe-test') && endsWith(github.event.comment.body, ':white_check_mark:') }}
            ${{ needs.binder-link.outputs.link }}
