name: Recipe Comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        if: |
          github.event.issue.pull_request && endsWith(github.event.comment.body, ':white_check_mark:')
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ endsWith(github.event.comment.body, ':white_check_mark:') }}
