name: Update Slash Command Comment
on:
  repository_dispatch:
    types: [prefect_webhook]
jobs:
  update_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Set emoji type from Flow status
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "$PAYLOAD_CONTEXT"
          if [[ ${{ github.event.client_payload.state }} == "Success" ]]; then
            echo "EDIT=:white_check_mark:" >> $GITHUB_ENV
          else
            echo "EDIT=:x:" >> $GITHUB_ENV
          fi

      - name: Add emoji to comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: "${{ github.event.client_payload.flow_run_id }}"
          body: |
            ${{ env.EDIT }}
